// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// BigColSums
NumericVector BigColSums(SEXP pBigMat);
RcppExport SEXP rfunctions_BigColSums(SEXP pBigMatSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type pBigMat(pBigMatSEXP);
    __result = Rcpp::wrap(BigColSums(pBigMat));
    return __result;
END_RCPP
}
